package com.example.sharding.entity;

public class TbTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.sharding_id
     *
     * @mbg.generated
     */
    private String shardingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.id
     *
     * @return the value of tb_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.id
     *
     * @param id the value for tb_test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.name
     *
     * @return the value of tb_test.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.name
     *
     * @param name the value for tb_test.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.sharding_id
     *
     * @return the value of tb_test.sharding_id
     *
     * @mbg.generated
     */
    public String getShardingId() {
        return shardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.sharding_id
     *
     * @param shardingId the value for tb_test.sharding_id
     *
     * @mbg.generated
     */
    public void setShardingId(String shardingId) {
        this.shardingId = shardingId == null ? null : shardingId.trim();
    }
}